### ISSUE TITLE
Error during python step_1_warmup_alpha.py

### ISSUE THREAD

**Issue by actruce** [lllyasviel/ToonDecompose#1]
I did this sript, but I have error message like this:

"Object 0 training start.
Training iter = 0.0
Traceback (most recent call last):
  File "step_1_warmup_alpha.py", line 218, in <module>
    debug_preview(object_id, config.temp_path + iter_flag + '.png')
  File "step_1_warmup_alpha.py", line 80, in debug_preview
    gt_label = LABELS[random_f, random_t, random_y, random_x]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)"

**Comment by actruce** [comment]
It is resolved when I used docker environment. It happened when I used conda environment.
